steps:
 # Build the container image $COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/s222475715sit72210hd/simplevideoapp:9'
      - '.'

  # Push container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/s222475715sit72210hd/simplevideoapp:9'
  
  # Deploy container image to GKE and delete existing pods
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - "run"
      - "--filename=deployment.yaml"
      - "--location=us-central1-c"
      - "--cluster=sit722"


